### ISSUE TITLE
getAccessToken() returns "invalid_request"

### ISSUE THREAD

**Issue by paperscissors** [cfreear/oauth2-mailchimp#1]
So after I get an authorization code successfully returned from the Mailchimp OAuth2 API, I try to do a getAccessToken, and get an "invalid_request" error returned.

I'm implementing the call as described in the PHP League docs for the parent library:

```
$client = new \CFreear\OAuth2\Client\Provider\MailChimp(
                array(
                    'clientId'          => $client_id,
                    'clientSecret'      => $client_secret
                )
            );

$token = $client->getAccessToken('authorization_code', array(
                    'code' => $authorization_code
                )
            );
```

I'm able to start the client and connect to the Mailchimp API, and do everything up to this point successfully.

I've also verified that you've got the correct `https://login.mailchimp.com/oauth2/token` endpoint defined for the getAccessToken call.

I'm kind of at a loss since all of my credentials are correct and work otherwise. Additionally the PHP League OAuth2 library works on every single other OAuth call I'm making to other services.

Thanks!

**Comment by paperscissors** [comment]
Okay, I figured it out after comparing the PHP League OAuth2 docs with the Mailchimp docs. Here it is for posterity:

The wrapper does not appear to pass the necessary client_id and client_secret keys, I think because the keys are different in the client call (clientId vs client_id) so I had to explicitly also call them all in the getAccessToken call to boot:

```
            $token = $client->getAccessToken('authorization_code', array(
                    'code' => $authorization_code,
                    'client_id' => $client_id,
                    'client_secret' => $client_secret,
                    'redirect_uri' => $redirect_uri
                )
            );
```

Not ideal but it works now.

**Comment by cfreear** [comment]
Unfortunately I'm not able to replicate this issue, could you provide more details on the "invalid_request" error you are getting? 

Even though we pass the client ID and secret into the provider constructor as `clientId` and `clientSecret` they are sent to MailChimp as `client_id` and `client_secret` as per the OAuth2 spec (see [thephpleague/oauth2-client/src/Provider/AbstractProvider:358](https://github.com/thephpleague/oauth2-client/blob/223d66f84ba817e03e6e075bee818892cd96c23a/src/Provider/AbstractProvider.php#L358)).

We also already pass `client_id` and `client_secret` as part of the `getAccessToken` call ([thephpleague/oauth2-client/src/Provider/AbstractProvider:552](https://github.com/thephpleague/oauth2-client/blob/223d66f84ba817e03e6e075bee818892cd96c23a/src/Provider/AbstractProvider.php#L552)) so I suspect the issue may lie somewhere else. 

Here's some pseudo code of the implementation I'm using successfully:

``` php
<?php
require_once "vendor/autoload.php";

session_start();

$provider = new CFreear\OAuth2\Client\Provider\MailChimp(array(
    'clientId'     => 'xxxxx',
    'clientSecret' => 'yyyyy',
    'redirectUri'  => 'http://localhost/'
));

if (!isset($_GET['code'])) {
    //no authorization code so redirect to mailchimp login
    $authUrl = $provider->getAuthorizationUrl();
    $_SESSION['oauth2state'] = $provider->getState();
    header('Location: '.$authUrl);
    exit;
} elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {
    //invalid response
    unset($_SESSION['oauth2state']);
    exit('Invalid state');
} else {
    try {
        $token = $provider->getAccessToken('authorization_code', [
            'code' => $_GET['code']
        ]);

        // Make use of token

        /**
         * @var $account \CFreear\OAuth2\Client\Provider\MailChimpResourceOwner
         */
        $account = $provider->getResourceOwner($token);

        // Use resource owner details 
    } catch (Exception $e) {
        // Failed to get the access token or user details.
        exit($e->getMessage());
    }
}
```

This is based on the [thephpleague/oauth2-client](https://github.com/thephpleague/oauth2-client) example, could you clarify how your implementation differs from this?

EDIT: I've specified `'redirectUri'  => 'http://localhost/'` in the example but in reality rederictUri is coming back to this script.

**Comment by cfreear** [comment]
Closing for now as 8 months have passed.
